### ISSUE TITLE
Exporting data using Put doesn't recognize UseFormat.

### ISSUE THREAD

**Issue by germancasares** [donnytian/Npoi.Mapper#31]
Was trying to insert a DateTime using Put, but It always returned me the numeric value of the Date.

I even reproduced it on the tests.

https://i.imgur.com/trrQhor.png

**Comment by german95n** [comment]
If you insert one row with put as override = true. It works.

But then if it is as override = false. It doesnt read the format properly.

**Comment by donnytian** [comment]
Hi, as you described, that's by design. If you don't set orverwrite as true, the format will not set to cell and you are using existing format in the worksheet, for a pure 'save` action that means the "existing format" is the NPOI/Excel default format.

So basically you can just keep overwrite as true and then it should be ok, if you have existing data in a workweek and want to keep them during the export, just make sure the column is set to expected format in existing worksheet, the mapper won't touch the format when you set overwrite as false.
