### ISSUE TITLE
Requesting Type Format support for nullable types when data in first row is null.

### ISSUE THREAD

**Issue by cda-1** [donnytian/Npoi.Mapper#5]
You [mentioned](https://github.com/donnytian/Npoi.Mapper/issues/4#issuecomment-269904292) in Issue #4 the new mapper.UseFormat() method. It works great on non-nullable types and on nullable types if the data in the first row after the header is not null. I tested with DateTime and DateTime?.

However, it does not apply the format if the data in the first row is null. In the case of DateTime? this results in integers being used in Excel instead of dates. Would support for this be feasible?

Also, thank you for implementing my previously-requested feature so quickly and I feel bad asking for more!

**Comment by donnytian** [comment]
Thanks for using and testing the tool!
This should be an issue and will look into these days.

发自我的 iPhone

在 2017年1月3日，上午1:04，Christopher Abichandani <notifications@github.com<mailto:notifications@github.com>> 写道：


You mentioned<https://github.com/donnytian/Npoi.Mapper/issues/4#issuecomment-269904292> in Issue #4<https://github.com/donnytian/Npoi.Mapper/issues/4> the new mapper.UseFormat() method. It works great on non-nullable types and on nullable types if the data in the first row after the header is not null. I tested with DateTime and DateTime?.

However, it does not apply the format if the data in the first row is null. In the case of DateTime? this results in integers being used in Excel instead of dates. Would support for this be feasible?

**Comment by donnytian** [comment]
Just realized that `UseFormat `for a `DateTime?` should not apply to `DateTime `property.

**Comment by donnytian** [comment]
Will release NuGet package in some days, or can someone help to test for import.
`UseFormat `should work if you have a `string `in a cell and want to be imported as `DateTime`, just specify the format with `UseFormat`. The trade-off is performance any way.
